sudo: required # ブラウザテスト用
language: php
dist: trusty # ブラウザテスト用

php:
  - 7.1.3 # Laravelが対応してるバージョンを指定

services:
  # DBはPostgreSQLを使用
  - postgresql

addons:
  chrome: beta # ブラウザテスト用

install:
  # Composerのパッケージをインストール
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  # DBを作成
  - psql -c 'create database travis_ci_test;' -U postgres

  # 環境設定をTravisCI用に変更
  - cp .env.travis .env

  # LaravelのAPP_KEYを生成
  - php artisan key:generate

script:
  # まず、ブラウザテストを実行
  - chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &
  - php artisan dusk

  # 単体テストとカバレッジ取得を実行
  - php artisan migrate --seed
  - ./vendor/bin/phpunit --coverage-clover clover.xml

after_success:
  # カバレッジをCodecovへ送る
  - bash <(curl -s https://codecov.io/bash) -cF php
